idle_bg = "#323232"
idle_fg = "#ffffff"
info_bg = "#323232"
info_fg = "#268bd2"
good_bg = "#323232"
good_fg = "#859900"
warning_bg = "#323232"
warning_fg = "#b58900"
critical_bg = "#323232"
critical_fg = "#dc322f"
separator = "\u007c"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
