idle_bg = "#3b4252"
idle_fg = "#E5E9F0"
info_bg = "#b48ead"
info_fg = "#2E3440"
good_bg = "#a3be8c"
good_fg = "#2E3440"
warning_bg = "#d08770"
warning_fg = "#2E3440"
critical_bg = "#bf616a"
critical_fg = "#2E3440"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
